import i18n from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';

i18n.use(LanguageDetector).use(initReactI18next).init({
    debug: true,
    lng: "en",
    fallbackLng: "en",
    returnObjects: true,
    resources: {
        en: {
            translation: {
                greeting: "Hello, Welcome",
                slogan: "Your ultimate farmers market!",
                languageLabel: "English",
                description: {
                    line1: "",
                    line2: ""
                },
                welcomeTo: "Welcome to",
                signInPrompt: "Please Sign-in to your account",
                noAccount: "Don't have an account yet?",
                fillApplication: "Fill up an Application",
                login: "Login",
                personalDetails: "Personal Details",
                associationDetails: "Association Details",
                credentialsUpload: "Credentials Upload",
                requestComplete: "Request Complete",
                next: "NEXT",
                back: "BACK",
                confirm: "CONFIRM",
                alreadyHaveAccount: "Already have an Account?",
                isRSBSARegistered: "Are you a (RSBSA) registered farmer?",
                uploadPersonalImage: "Upload Personal Image",
                uploadAssociationPhoto: "Upload Association Photo",
                totalSales: "Total Sales",
                products: "Products",
                deals: "Deals",
                pendingDeals: "Pending Deals",
                recentTradersMessages: "Recent Traders Messages",
                viewAll: "View All",
                daysAgo: "days ago",
                recentOffers: "Recent Offers",
                productName: "Product Name",
                price: "Price",
                expectedYield: "Expected Yield",
                shippingMethod: "Shipping Method",
                status: "Status",
                action: "Action"
            },
        },
        tl: {
            translation: {
                greeting: "Tagalog Greeting",
                slogan: "ANG IYONG PINAKA-MAGANDANG PAMILIHAN SA MAGSASAKA!",
                languageLabel: "Tagalog",
                welcomeTo: "Maligayang pagdating sa",
                signInPrompt: "Mangyaring mag-sign in sa iyong account",
                noAccount: "Wala ka pang account?",
                fillApplication: "Punan ang isang Aplikasyon",
                login: "Mag-login",
                personalDetails: "Personal na Detalye",
                associationDetails: "Mga Detalye ng Asosasyon",
                credentialsUpload: "Pag-upload ng Mga Kredensyal",
                requestComplete: "Kumpleto na ang Kahilingan",
                next: "SUNOD",
                back: "BALIK",
                confirm: "KUMPIRMADO",
                alreadyHaveAccount: "May Account na ba?",
                isRSBSARegistered: "Ikaw ba ay isang rehistradong magsasaka ng (RSBSA)?",
                uploadPersonalImage: "I-upload ang Personal na Imahe",
                uploadAssociationPhoto: "I-upload ang Larawan ng Asosasyon",
                totalSales: "Kabuuang Benta",
                products: "Mga Produkto",
                deals: "Mga Kasunduan",
                pendingDeals: "Mga Naka-pending na Kasunduan",
                recentTradersMessages: "Mga Kamakailang Mensahe ng Mga Mangangalakal",
                viewAll: "Tingnan Lahat",
                daysAgo: "mga araw na nakalipas",
                recentOffers: "Mga Kamakailang Alok",
                productName: "Pangalan ng Produkto",
                price: "Presyo",
                expectedYield: "Inaasahang Ani",
                shippingMethod: "Paraan ng Pagpapadala",
                status: "Katayuan",
                action: "Aksyon"
            },
        },
        bs: {
            translation: {
                greeting: "Bisaya Greeting",
                slogan: "Ang imong pinakalabing maayo nga merkado sa mga mag-uuma!",
                languageLabel: "Bisaya",
                welcomeTo: "Maayong pag-abot sa",
                signInPrompt: "Palihug pag-sign in sa imong account",
                noAccount: "Wala pa kay account?",
                fillApplication: "Pagpuno sa usa ka Aplikasyon",
                login: "Pag-login",
                personalDetails: "Personal nga Detalye",
                associationDetails: "Mga Detalye sa Asosasyon",
                credentialsUpload: "Pag-upload sa mga Kredensyal",
                requestComplete: "Humana na ang Hangyo",
                next: "SUNOD",
                back: "BALIK",
                confirm: "KUMPIRMA",
                alreadyHaveAccount: "Aduna na ba kay Account?",
                isRSBSARegistered: "Usa ka ba ka rehistradong mag-uuma sa (RSBSA)?",
                uploadPersonalImage: "I-upload ang Personal nga Imahe",
                uploadAssociationPhoto: "I-upload ang Larawan sa Asosasyon",
                totalSales: "Kinatibuk-ang Baligya",
                products: "Mga Produkto",
                deals: "Mga Kasabutan",
                pendingDeals: "Pending nga mga Kasabutan",
                recentTradersMessages: "Bag-ong mga Mensahe sa Mag-uuma",
                viewAll: "Tan-awa Tanan",
                daysAgo: "mga adlaw na ang milabay",
                recentOffers: "Bag-ong Mga nagtanyag",
                productName: "Pangalan sa Produkto",
                price: "Presyo",
                expectedYield: "Gilauman nga Ani",
                shippingMethod: "Paraan sa Pagpadala",
                status: "Estado",
                action: "Aksyon"
            },
        },
    },
    
});
